# Generated by Django 4.2.7 on 2026-03-31 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'xp_reward'],
            },
        ),
        migrations.CreateModel(
            name='StockPredictionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200)),
                ('stock_symbol', models.CharField(max_length=20, unique=True)),
                ('question', models.TextField()),
                ('chart_data', models.JSONField(default=list)),
                ('expected_direction', models.CharField(choices=[('up', 'Upward Trend'), ('down', 'Downward Trend'), ('neutral', 'Neutral/Flat')], default='neutral', max_length=10)),
                ('expected_keywords', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('base_score', models.IntegerField(default=10)),
                ('max_score', models.IntegerField(default=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('xp', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('financial_goal', models.CharField(blank=True, choices=[('long_term_wealth', 'Build long-term wealth'), ('specific_goals', 'Save for specific goals'), ('learning', 'Just learning for now'), ('extra_income', 'Generate extra income')], max_length=50)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('safe', 'Play it safe'), ('balanced', 'Balanced approach'), ('aggressive', 'Higher returns, higher risk')], max_length=20)),
                ('investment_experience', models.CharField(blank=True, choices=[('beginner', 'Complete beginner'), ('basics', 'Know the basics'), ('experienced', 'Fairly experienced'), ('very_experienced', 'Very experienced')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('less_than_1', 'Less than 1 year'), ('1_to_5', '1-5 years'), ('5_plus', '5+ years')], max_length=20)),
                ('initial_investment', models.CharField(blank=True, choices=[('under_10k', 'Under ₹10,000'), ('10k_50k', '₹10,000 - ₹50,000'), ('50k_1lakh', '₹50,000 - ₹1,00,000'), ('above_1lakh', 'Above ₹1,00,000')], max_length=20)),
                ('streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp'],
            },
        ),
        migrations.CreateModel(
            name='StockPredictionChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('prediction', models.TextField()),
                ('prediction_direction', models.CharField(default='neutral', max_length=10)),
                ('ai_analysis', models.TextField(blank=True)),
                ('ai_direction', models.CharField(default='neutral', max_length=20)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_data', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictedStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('category', models.CharField(default='Unknown', max_length=50)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('market_cap', models.CharField(default='N/A', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_history', models.JSONField(blank=True, default=list)),
                ('ml_direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('ml_confidence', models.FloatField(default=0.5)),
                ('ml_regime', models.CharField(default='Unknown', max_length=20)),
                ('ml_volatility', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='users_predi_symbol_5d82f3_idx'), models.Index(fields=['last_updated'], name='users_predi_last_up_8ab1a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Financial Goal', max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_sip', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('time_to_goal_months', models.IntegerField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, default='wallet', max_length=50)),
                ('color', models.CharField(blank=True, default='from-brand-primary to-orange-500', max_length=100)),
                ('icon_bg', models.CharField(blank=True, default='bg-brand-50 text-brand-600', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('holdings', models.JSONField(default=dict)),
                ('total_value', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('stock_type', models.CharField(choices=[('penny', 'Penny Stock'), ('volatile', 'Highly Volatile'), ('stable', 'Stable Blue Chip'), ('growth', 'Growth Stock'), ('dividend', 'Dividend Stock'), ('tech', 'Tech Stock'), ('finance', 'Finance Stock'), ('energy', 'Energy Stock')], default='stable', max_length=20)),
                ('sector', models.CharField(default='General', max_length=100)),
                ('category', models.CharField(default='Mid Cap', max_length=50)),
                ('volatility', models.FloatField(default=0.02)),
                ('trend', models.CharField(default='neutral', max_length=10)),
                ('trend_strength', models.FloatField(default=0.0)),
                ('price_history', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('market_cap', models.CharField(default='N/A', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='users_custo_symbol_75ac80_idx'), models.Index(fields=['stock_type'], name='users_custo_stock_t_abca89_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('stock_score', models.IntegerField(default=0)),
                ('scenario_score', models.IntegerField(default=0)),
                ('total_predictions', models.IntegerField(default=0)),
                ('correct_predictions', models.IntegerField(default=0)),
                ('scenario_attempts', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score', '-current_streak'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('module_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('flashcards_flipped', models.IntegerField(default=0)),
                ('mcqs_progress', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'course_id', 'module_id')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
