# Generated by Django 5.2.12 on 2026-09-21 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpredictionchallenge',
            name='confidence',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='stockpredictionchallenge',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='users.stockpredictionquestion'),
        ),
    ]
