# Generated by Django 4.2.7 on 2025-11-21 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        # Step 1: Create new models first
        migrations.CreateModel(
            name='DemoPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdings', models.JSONField(default=dict)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('xp', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('financial_goal', models.CharField(blank=True, choices=[('long_term_wealth', 'Build long-term wealth'), ('specific_goals', 'Save for specific goals'), ('learning', 'Just learning for now'), ('extra_income', 'Generate extra income')], max_length=30)),
                ('investment_experience', models.CharField(blank=True, choices=[('beginner', 'Complete beginner'), ('basics', 'Know the basics'), ('experienced', 'Fairly experienced'), ('very_experienced', 'Very experienced')], max_length=30)),
                ('risk_comfort', models.CharField(blank=True, choices=[('safe', 'Play it safe'), ('balanced', 'Balanced approach'), ('aggressive', 'Higher returns, higher risk')], max_length=20)),
                ('initial_investment', models.CharField(blank=True, choices=[('under_10k', 'Under ₹10,000'), ('10k_50k', '₹10,000 - ₹50,000'), ('50k_2l', '₹50,000 - ₹2,00,000'), ('over_2l', 'Over ₹2,00,000')], max_length=20)),
                ('investment_timeline', models.CharField(blank=True, choices=[('less_than_1', 'Less than 1 year'), ('1_to_5', '1-5 years'), ('5_plus', '5+ years')], max_length=20)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('demo_balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-xp'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demoportfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_portfolio', to=settings.AUTH_USER_MODEL),
        ),
        # Step 2: Remove old ForeignKey fields from UserProgress FIRST
        migrations.RemoveIndex(
            model_name='userprogress',
            name='users_userp_user_id_3ab26c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprogress',
            name='users_userp_user_id_563d96_idx',
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='topic',
        ),
        # Step 3: NOW add new CharField fields (no conflict anymore)
        migrations.AddField(
            model_name='userprogress',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='module_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='xp_awarded',
            field=models.IntegerField(default=0),
        ),
        # Step 4: Update QuizAttempt
        migrations.RemoveField(
            model_name='quizattempt',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='course_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='module_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz_data',
            field=models.JSONField(default=dict),
        ),
        # Step 5: Update status field and indexes
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course_id', 'module_id')},
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'course_id'], name='users_userp_user_id_3ab26c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'course_id', 'module_id'], name='users_userp_user_id_35ea82_idx'),
        ),
    ]
