# Generated by Django 4.2.7 on 2025-11-21 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_demoportfolio_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoportfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='demoportfolio',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='initial_investment',
            field=models.CharField(blank=True, choices=[('under_10k', 'Under ₹10,000'), ('10k_50k', '₹10,000 - ₹50,000'), ('50k_1lakh', '₹50,000 - ₹1,00,000'), ('above_1lakh', 'Above ₹1,00,000')], max_length=20),
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('smartphone', 'Smartphone'), ('plane', 'Plane'), ('home', 'Home'), ('car', 'Car'), ('graduation-cap', 'Graduation'), ('gem', 'Gem'), ('lightbulb', 'Lightbulb'), ('wallet', 'Wallet')], default='wallet', max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_sip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_to_goal_months', models.IntegerField()),
                ('color', models.CharField(default='from-brand-primary to-orange-500', max_length=50)),
                ('icon_bg', models.CharField(default='bg-brand-50 text-brand-600', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
