# Generated by Django 5.2.12 on 2026-09-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stockpredictionchallenge_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoportfolio',
            name='last_contribution_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demoportfolio',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='demoportfolio',
            name='total_contributed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='monthly_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='plan_choice',
            field=models.CharField(default='balanced', max_length=16),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
