# Generated by Django 5.2.12 on 2026-09-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_demoportfolio_last_contribution_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=4, default=0.068, max_digits=5)),
                ('tenure_months', models.IntegerField(default=12)),
                ('opened_on', models.DateField(auto_now_add=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('broken_early', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='users.demoportfolio')),
            ],
            options={
                'ordering': ['-opened_on'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('index', 'Nifty 50 index fund'), ('midcap', 'Nifty Midcap 150 index fund'), ('gold', 'Gold'), ('debt', 'Short-duration debt fund')], default='index', max_length=16)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.FloatField(default=0.0)),
                ('invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('started_on', models.DateField(auto_now_add=True)),
                ('last_run_on', models.DateField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to='users.demoportfolio')),
            ],
            options={
                'ordering': ['-started_on'],
            },
        ),
    ]
