# Generated by Django 4.2.7 on 2026-04-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_portfoliofollow_traderationalepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCrisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_balance', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('difficulty', models.CharField(default='Hard', max_length=20)),
                ('icon', models.CharField(default='flame', max_length=50)),
                ('narrative_intro', models.TextField(blank=True)),
                ('recovery_period_months', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCapsuleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_sim_day', models.IntegerField(default=0)),
                ('portfolio_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('holdings', models.JSONField(default=dict)),
                ('equity_curve', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('final_score', models.IntegerField(default=0)),
                ('survival_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.historicalcrisis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_capsule_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_day', models.IntegerField(default=0)),
                ('headline', models.CharField(max_length=300)),
                ('impact_description', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='users.historicalcrisis')),
            ],
            options={
                'verbose_name_plural': 'Historical News',
                'ordering': ['relative_day'],
            },
        ),
    ]
