# Generated by Django 4.2.7 on 2026-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalcrisis_timecapsulesession_historicalnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='flashcards_flipped',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
