# Generated by Django 4.2.7 on 2025-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_stockpredictionchallenge_challengeleaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('category', models.CharField(default='Unknown', max_length=50)),
                ('sector', models.CharField(default='Unknown', max_length=100)),
                ('market_cap', models.CharField(default='N/A', max_length=50)),
                ('price_history', models.JSONField(blank=True, default=list)),
                ('ml_direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('ml_confidence', models.FloatField(default=0.5)),
                ('ml_regime', models.CharField(default='Unknown', max_length=20)),
                ('ml_volatility', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='users_predi_symbol_5d82f3_idx'), models.Index(fields=['last_updated'], name='users_predi_last_up_8ab1a3_idx')],
            },
        ),
    ]
