# Generated by Django 4.2.7 on 2026-04-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_stockpredictionquestion_hint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='category',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='strategy_report',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
