# Generated by Django 5.2.8 on 2025-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_predictedstockdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedstockdata',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
