# Generated by Django 5.2.8 on 2025-11-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_modulecontent_modulemcq_userplaquecardcompletion_and_more'),
        ('users', '0012_add_scenario_scores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('xp_reward', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'xp_reward'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='financialgoal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'ordering': ['-last_accessed']},
        ),
        migrations.RemoveIndex(
            model_name='userprogress',
            name='users_userp_user_id_3ab26c_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprogress',
            name='users_userp_user_id_35ea82_idx',
        ),
        migrations.RenameIndex(
            model_name='customstock',
            new_name='users_custo_symbol_75ac80_idx',
            old_name='users_custo_symbol_idx',
        ),
        migrations.RenameIndex(
            model_name='customstock',
            new_name='users_custo_stock_t_abca89_idx',
            old_name='users_custo_stock_t_idx',
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='color',
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='icon_bg',
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='financialgoal',
            name='time_to_goal_months',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='demo_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='investment_timeline',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='onboarding_completed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='risk_comfort',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='created_at',
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='title',
            field=models.CharField(default='Financial Goal', max_length=200),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='challengeleaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_leaderboard', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='monthly_sip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockpredictionchallenge',
            name='ai_direction',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockpredictionchallenge',
            name='prediction_direction',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='financial_goal',
            field=models.CharField(blank=True, choices=[('long_term_wealth', 'Build long-term wealth'), ('specific_goals', 'Save for specific goals'), ('learning', 'Just learning for now'), ('extra_income', 'Generate extra income')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Complete beginner'), ('basics', 'Know the basics'), ('experienced', 'Fairly experienced'), ('very_experienced', 'Very experienced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='flashcards_flipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='module_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
