# Generated by Django 5.2.8 on 2025-11-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_achievement_userachievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='color',
            field=models.CharField(blank=True, default='from-brand-primary to-orange-500', max_length=100),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='icon',
            field=models.CharField(blank=True, default='wallet', max_length=50),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='icon_bg',
            field=models.CharField(blank=True, default='bg-brand-50 text-brand-600', max_length=100),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='time_to_goal_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
