# Generated by Django 4.2.7 on 2026-03-31 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_ids', models.CharField(max_length=100)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_balance', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserScenarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_option', models.CharField(blank=True, max_length=200, null=True)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('points_earned', models.IntegerField(default=0)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_played'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('decision_type', models.CharField(choices=[('INVEST', 'Invest'), ('SAVE', 'Save'), ('SPEND', 'Spend')], max_length=10)),
                ('balance_impact', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_delta', models.IntegerField(default=0)),
                ('risk_score_delta', models.IntegerField(default=0)),
                ('future_growth_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('score', models.IntegerField(default=0, help_text='Points awarded for this choice (0-20)')),
                ('why_it_matters', models.TextField()),
                ('mentor_feedback', models.CharField(max_length=255)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='UserScenarioAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_earned', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.decisionoption')),
                ('quiz_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulator.quizrun')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', 'scenario'], name='simulator_u_user_id_8af316_idx'), models.Index(fields=['user', 'attempted_at'], name='simulator_u_user_id_1daa0e_idx')],
                'unique_together': {('user', 'scenario', 'quiz_run')},
            },
        ),
    ]
