# Generated by Django 5.2.12 on 2026-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrun',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
    ]
