# Generated by Django 4.2.7 on 2026-04-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0002_virtualportfolio_portfoliotransaction_portfolioasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualportfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=15),
        ),
    ]
