# Generated by Django 5.2.8 on 2025-11-21 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_userscenarioprogress_userscenariocustomization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userscenarioprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userscenarioprogress',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='userscenarioprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='score',
            field=models.IntegerField(default=0, help_text='Points awarded for this choice (0-20)'),
        ),
        migrations.AddField(
            model_name='userscenariolog',
            name='chosen_option',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userscenariolog',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='balance_impact',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='confidence_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='future_growth_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='mentor_feedback',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='risk_score_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='why_it_matters',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='QuizRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_ids', models.CharField(max_length=100)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserScenarioCustomization',
        ),
        migrations.DeleteModel(
            name='UserScenarioProgress',
        ),
    ]
