# Generated by Django 4.2.7 on 2026-04-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0003_alter_virtualportfolio_cash_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='position_type',
            field=models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], default='LONG', max_length=10),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('SHORT', 'Short Sell'), ('COVER', 'Buy to Cover'), ('STOP_LOSS', 'Stop Loss')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together={('portfolio', 'symbol', 'position_type')},
        ),
    ]
