# Generated by Django 5.2.8 on 2025-11-25 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0004_alter_userscenarioprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrun',
            name='xp_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decisionoption',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='UserScenarioAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_earned', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('xp_awarded', models.IntegerField(default=0)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.decisionoption')),
                ('quiz_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='simulator.quizrun')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', 'scenario'], name='simulator_u_user_id_8af316_idx'), models.Index(fields=['user', 'attempted_at'], name='simulator_u_user_id_1daa0e_idx')],
                'unique_together': {('user', 'scenario', 'quiz_run')},
            },
        ),
    ]
