import json
import random
from users.ml_predictor import ML_PREDICTOR
from mentor_engine.gemini_client import gemini_chat_json
from .models import Scenario, DecisionOption

TICKERS = ["AAPL", "GOOGL", "MSFT", "TSLA", "RELIANCE.NS", "HDFCBANK.NS"]

def generate_dynamic_scenario(user=None):
    symbol = random.choice(TICKERS)
    
    # 1. Get Live ML Prediction
    prediction = ML_PREDICTOR.predict(symbol)
    
    # 2. Ask Gemini to Generate a Scenario based on this prediction
    prompt = f"""
    You are an expert financial quiz generator. Return ONLY raw JSON without markdown.
    A user is trading {symbol}. The market ML model predicts:
    - Direction: {prediction['direction']} (Confidence: {prediction['confidence']:.2f})
    - Volatility: {prediction['vol']:.4f}
    - Regime: {prediction['regime']}

    Create a short scenario for a paper trading quiz and 3 distinct options for the user to pick from. 
    Use this strict JSON format:
    {{
      "title": "Trading {symbol} in {prediction['regime']}",
      "description": "Short description of the setup...",
      "options": [
        {{
          "text": "Option text (Safe)",
          "decision_type": "SAVE",
          "score": 10,
          "balance_impact": 0,
          "why_it_matters": "...",
          "mentor_feedback": "..."
        }},
        {{
          "text": "Option text (Aggressive/Risky)",
          "decision_type": "INVEST",
          "score": 0,
          "balance_impact": -5000,
          "why_it_matters": "...",
          "mentor_feedback": "..."
        }},
        {{
          "text": "Option text (Balanced - BEST choice)",
          "decision_type": "INVEST",
          "score": 20,
          "balance_impact": -2000,
          "why_it_matters": "...",
          "mentor_feedback": "..."
        }}
      ]
    }}
    IMPORTANT: Return valid JSON ONLY. No markdown, no explanation.
    """
    
    try:
        data = gemini_chat_json(prompt)
        
        # 3. Save to DB
        scenario = Scenario.objects.create(
            title="[LIVE AI] " + data.get('title', f"Trading {symbol}"),
            description=data.get('description', 'Dynamic scenario generated by AI.'),
            starting_balance=50000
        )
        
        opts = data.get('options', [])
        for opt in opts:
            DecisionOption.objects.create(
                scenario=scenario,
                text=opt.get('text', 'Placeholder'),
                decision_type=opt.get('decision_type', 'INVEST'),
                balance_impact=opt.get('balance_impact', 0),
                score=opt.get('score', 0),
                why_it_matters=opt.get('why_it_matters', ''),
                mentor_feedback=opt.get('mentor_feedback', '')
            )
        return scenario.id
    except Exception as e:
        print(f"[Dynamic Scenario Error] {e}")
        return None
