# Generated by Django 5.2.12 on 2026-09-17 06:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_date', models.DateField(db_index=True)),
                ('kind', models.CharField(choices=[('ticker', 'Ticker Tiles'), ('call', 'Market Call'), ('estimate', 'Number Sense')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('solution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-puzzle_date'],
                'indexes': [models.Index(fields=['puzzle_date', 'kind'], name='daily_daily_puzzle__cb6934_idx')],
                'unique_together': {('puzzle_date', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('longest', models.IntegerField(default=0)),
                ('last_active', models.DateField(blank=True, null=True)),
                ('freezes', models.IntegerField(default=1)),
                ('total_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guesses', models.JSONField(default=list)),
                ('solved', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='daily.dailypuzzle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'puzzle'], name='daily_puzzl_user_id_ac503e_idx')],
                'unique_together': {('user', 'puzzle')},
            },
        ),
        migrations.CreateModel(
            name='ReviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('module_id', models.CharField(max_length=100)),
                ('question_id', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_index', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('ease', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('due_on', models.DateField(db_index=True, default=datetime.date.today)),
                ('lapses', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_on'],
                'indexes': [models.Index(fields=['user', 'due_on'], name='daily_revie_user_id_d9dd71_idx')],
                'unique_together': {('user', 'question_id')},
            },
        ),
    ]
