# Generated by Django 5.2.12 on 2026-09-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypuzzle',
            name='kind',
            field=models.CharField(choices=[('ticker', 'Ticker Tiles'), ('call', 'Market Call'), ('estimate', 'Number Sense'), ('ledger', 'Ledger'), ('rank', 'Rank It')], max_length=16),
        ),
    ]
