# Generated by Django 5.2.12 on 2026-09-17 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=100)),
                ('module_id', models.CharField(blank=True, max_length=100)),
                ('sender', models.CharField(choices=[('user', 'Learner'), ('nex', 'Nex')], max_length=10)),
                ('text', models.TextField()),
                ('time_display', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'course_id', 'module_id'], name='chat_topicc_user_id_e0d947_idx')],
            },
        ),
    ]
