# Generated by Django 5.2.12 on 2026-09-17 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('module_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('answered_questions', models.JSONField(blank=True, default=list)),
                ('reviewed_cards', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user course progress',
                'indexes': [models.Index(fields=['user', 'course_id'], name='courses_use_user_id_35c5b3_idx'), models.Index(fields=['user', 'status'], name='courses_use_user_id_732351_idx')],
                'unique_together': {('user', 'course_id', 'module_id')},
            },
        ),
    ]
