"""
The course catalogue.

Content lives on disk at ``course_modules/<course>/<module>/{flash_cards,mcqs,qna}.json``.
This module is the only thing that reads it, and it is the store the mentor
resolves against.

Two problems this replaces:

* The catalogue was re-read from ~96 JSON files on every request. It is now
  parsed once and cached.
* A second, unrelated store (``financial_course.json``, four courses about chart
  patterns) was what the mentor searched. Since the real course ids were never
  in it, every question came back "Course 'investing-basics' not found."
"""

from __future__ import annotations

import json
import logging
import re
from functools import lru_cache
from pathlib import Path

from django.conf import settings

logger = logging.getLogger(__name__)

CONTENT_ROOT = Path(settings.BASE_DIR) / 'course_modules'

# Title and level per course folder. A folder with no entry still loads, titled
# from its slug, so adding content does not require editing code.
COURSE_META = {
    'money-basics': ('Money Basics', 'beginner'),
    'budgeting': ('Budgeting & Saving', 'beginner'),
    'banking-products': ('Banking Products', 'beginner'),
    'investing-basics': ('Investing Basics', 'beginner'),
    'investing-101': ('Investing 101', 'beginner'),
    'stock-market-101': ('Stock Market 101', 'beginner'),
    'mutual-funds-sips': ('Mutual Funds & SIPs', 'beginner'),
    'emergency-insurance': ('Emergency Fund & Insurance', 'beginner'),
    'financial-goals': ('Financial Goals', 'beginner'),
    'scams-safety': ('Scams & Safety', 'beginner'),
    'debt-credit': ('Debt & Credit', 'intermediate'),
    'stocks-etfs': ('Stocks & ETFs', 'intermediate'),
    'tax-planning': ('Tax Planning', 'intermediate'),
    'retirement': ('Retirement Planning', 'intermediate'),
    'portfolio-building': ('Portfolio Building', 'intermediate'),
    'behavioral-finance': ('Money Psychology', 'intermediate'),
    'market-fundamentals': ('Market Fundamentals', 'intermediate'),
    'risk-management': ('Risk Management', 'intermediate'),
    'real-estate': ('Real Estate Basics', 'advanced'),
    'crypto-alternatives': ('Crypto & Alternatives', 'advanced'),
    'options-strategies': ('Options Strategies', 'advanced'),
    'derivatives-futures': ('Derivatives & Futures', 'advanced'),
    'portfolio-optimization': ('Portfolio Optimization', 'advanced'),
    'valuation-modeling': ('Valuation Modeling', 'advanced'),
    'macro-and-cycles': ('Macro Trends & Market Cycles', 'advanced'),
}

XP_TO_UNLOCK = {'beginner': 0, 'intermediate': 750, 'advanced': 1200}

# Content was generated by an LLM and its artifacts were never stripped, so
# "[Image of an inflation chart...]" shipped to users as body copy.
_IMAGE_ARTIFACT = re.compile(r'\[(?:Image|Chart|Diagram|Graph)[^\]]*\]', re.IGNORECASE)

# LaTeX also leaked into prose: "a $\text{₹}1,00,000$ limit". Worse, the source
# JSON wrote the backslash unescaped, so JSON parsing turned "\t" into a real
# tab and the text now reads TAB + "ext{₹}". Both forms are repaired.
# \x09 is the tab; written in hex so it is not mistaken for the "\t" of "\text".
_LATEX_TAB_MANGLED = re.compile(r'\x09(?=ext\s*\{)')
_LATEX_COMMAND = re.compile(r'\\?(?:text|textbf|mathrm|mathbf)\s*\{([^}]*)\}')
_LATEX_MATH = re.compile(r'\$+([^$]*)\$+')

_LATEX_LITERALS = {'\\%': '%', '\\times': '×', '\\,': '', '\\ ': ' '}


def clean(text: str | None) -> str:
    """Strip generation artifacts and normalise whitespace.

    Markdown emphasis is left intact — the client renders it. It used to be
    printed literally, so learners read asterisks around "Inflation".
    """
    if not text:
        return ''

    text = _IMAGE_ARTIFACT.sub('', text)

    # Put the "t" back that JSON's tab escape ate, then unwrap normally.
    text = _LATEX_TAB_MANGLED.sub('t', text)
    text = _LATEX_COMMAND.sub(r'\1', text)
    text = _LATEX_MATH.sub(r'\1', text)

    for literal, replacement in _LATEX_LITERALS.items():
        text = text.replace(literal, replacement)

    return re.sub(r'\s+', ' ', text).strip()


def _read_json(path: Path) -> list:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding='utf-8'))
    except (json.JSONDecodeError, OSError):
        logger.warning('could not read %s', path, exc_info=True)
        return []
    return data if isinstance(data, list) else []


def _load_cards(path: Path) -> list[dict]:
    """Turn theory entries into two-sided recall cards.

    The stored shape is ``{topic, theory_title, theory_content}``. The old UI
    rendered ``theory_content`` face-up under the heading "EXPERT ANSWER" —
    identical to the theory block directly above it, so there was nothing to
    recall. The prompt goes on the front and the explanation on the back.
    """
    cards = []
    for index, entry in enumerate(_read_json(path)):
        back = clean(entry.get('theory_content'))
        if not back:
            continue
        cards.append(
            {
                'id': entry.get('id') or f'card-{index}',
                'term': clean(entry.get('topic')) or f'Card {index + 1}',
                'prompt': clean(entry.get('theory_title')) or clean(entry.get('topic')),
                'answer': back,
            }
        )
    return cards


def _load_mcqs(path: Path) -> list[dict]:
    """Normalise questions to an index-based answer.

    Stored as the correct option's full text, which breaks silently on any
    whitespace difference. Resolved to an index once, here.
    """
    questions = []
    for index, entry in enumerate(_read_json(path)):
        options = [clean(o) for o in entry.get('options', []) if o]
        answer = clean(entry.get('correct_answer'))
        if len(options) < 2 or answer not in options:
            logger.warning('skipping malformed MCQ %s in %s', entry.get('id'), path)
            continue

        feedback = entry.get('ai_feedback') or {}
        questions.append(
            {
                'id': entry.get('id') or f'mcq-{index}',
                'question': clean(entry.get('question')),
                'options': options,
                'correct_index': options.index(answer),
                'explanation': clean(feedback.get('correct')),
                'hint': clean(feedback.get('incorrect')),
            }
        )
    return questions


def _load_qna(path: Path) -> list[dict]:
    """Common questions. Both stored key spellings are accepted."""
    pairs = []
    for entry in _read_json(path):
        question = clean(entry.get('question') or entry.get('q'))
        answer = clean(entry.get('answer') or entry.get('a'))
        if question and answer:
            pairs.append({'question': question, 'answer': answer})
    return pairs


def _load_module(course_id: str, path: Path, order: int) -> dict:
    cards = _load_cards(path / 'flash_cards.json')
    mcqs = _load_mcqs(path / 'mcqs.json')
    qna = _load_qna(path / 'qna.json')

    # The first card's prompt is the module's headline, and its answer is the
    # theory the module teaches.
    title = cards[0]['prompt'] if cards else path.name.upper()
    theory = '\n\n'.join(card['answer'] for card in cards)

    return {
        'id': path.name,
        'course_id': course_id,
        'title': title,
        'order': order,
        'summary': (qna[0]['answer'][:180] if qna else theory[:180]),
        'theory': theory,
        'cards': cards,
        'mcqs': mcqs,
        'qna': qna,
        'xp_reward': 50 + order * 25,
        'estimated_minutes': max(3, len(cards) * 2 + len(mcqs)),
    }


@lru_cache(maxsize=1)
def catalogue() -> list[dict]:
    """Every course with its modules. Parsed once per process.

    Call :func:`reload` after editing content on disk.
    """
    if not CONTENT_ROOT.exists():
        logger.error('course content directory missing: %s', CONTENT_ROOT)
        return []

    courses = []
    for folder in sorted(CONTENT_ROOT.iterdir()):
        if not folder.is_dir():
            continue

        title, level = COURSE_META.get(
            folder.name, (folder.name.replace('-', ' ').title(), 'beginner')
        )

        modules = [
            _load_module(folder.name, module_path, order)
            for order, module_path in enumerate(sorted(p for p in folder.iterdir() if p.is_dir()), start=1)
        ]
        if not modules:
            continue

        courses.append(
            {
                'id': folder.name,
                'title': title,
                'level': level,
                'xp_to_unlock': XP_TO_UNLOCK[level],
                'summary': modules[0]['summary'],
                'modules': modules,
                'module_count': len(modules),
                'estimated_minutes': sum(m['estimated_minutes'] for m in modules),
            }
        )

    logger.info('loaded %s courses from %s', len(courses), CONTENT_ROOT)
    return courses


def reload() -> None:
    """Clear the parsed catalogue. Used by the content import command."""
    catalogue.cache_clear()


def get_course(course_id: str) -> dict | None:
    return next((c for c in catalogue() if c['id'] == course_id), None)


def get_module(course_id: str, module_id: str) -> dict | None:
    course = get_course(course_id)
    if not course:
        return None
    return next((m for m in course['modules'] if m['id'] == module_id), None)


def next_module(course_id: str, module_id: str) -> dict | None:
    """The module after this one, or ``None`` at the end of a course.

    Lessons used to end at the FAQ with no way forward.
    """
    course = get_course(course_id)
    if not course:
        return None

    modules = course['modules']
    position = next((i for i, m in enumerate(modules) if m['id'] == module_id), None)
    if position is None or position + 1 >= len(modules):
        return None

    following = modules[position + 1]
    return {'id': following['id'], 'title': following['title'], 'course_id': course_id}
